contentfeed/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Page urls
    path('',views.ContentFeed,{"t_view": 0}, name='home'),
    path('new',views.ContentFeed,{"t_view": 1}, name='newest'),
    path('random',views.ContentFeed,{"t_view": 2}, name='random'),
    path('old',views.ContentFeed,{"t_view": 3}, name='oldest'),
    path('about',views.about,name='about'),
    path('sites',views.sites, name='sites'),
    path('search',views.search, name='search'),
    path('publication/<uuid:pubid>',views.PublicationLookup, name='publication_lookup'),
    # Error Pages
    path('404',views.Error404, name='404page'),
    path('500',views.Error500, name='500page'),
    # Function urls
    path('feature/<item_uid>/',views.ItemFeatured,name='feature'),
    path('hide/<item_uid>/',views.ItemHidden,name='hide'),
    path('vote/<uuid:item_id>/<session_id>/',views.Vote,name='vote')
]

contentfeed/models.py
import pkgutil
from tabnanny import verbose
import uuid                         # needed for keys
from django.db import models        # standard
from django.utils import timezone   # needed for time delta 

# Source Type (i.e. RSS)
class SourceType(models.Model):
    # Fields 
    type_id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this content source type", verbose_name="Type Id" )
    type_name = models.CharField(max_length=256,blank=False,null=False, help_text="The name of the source type i.e RSS", verbose_name="Type Name")
    type_hidden = models.BooleanField(default=False, help_text="A flag to determine whether this item should be hidden from the site", verbose_name="Type Hidden")
    # Metadata
    class Meta:
        db_table = "source_type"
        ordering = ['type_name']
        verbose_name = "Source Type"
        verbose_name_plural = "Source Types"
    # Methods
    def __str__(self):
        return self.type_name

# Publications (i.e. SuperJump Magazine)
class Publications(models.Model):
    # Fields
    pub_id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this publication", verbose_name="Publication Id")
    pub_name = models.CharField(max_length=256,blank=False,null=False,help_text="The name of the publication i.e SuperJump Magazine", verbose_name="Publication Name") 
    pub_url = models.URLField(blank=False,null=False, help_text="URL of the publication, i.e the top level domain", verbose_name="Publication URL")#convert to ip address
    pub_feedurl = models.URLField(blank=False,null=False,help_text="URL of the feed, i.e rss", verbose_name="Publication Feed URL")
    pub_feedtype = models.ForeignKey(SourceType,on_delete=models.RESTRICT,null=True,help_text="The type of feed it is for automation", verbose_name="Feed Type")
    pub_description = models.TextField(max_length=2000, blank=False,null=False, help_text="Description of the publication, used in the sources page", verbose_name="Publication Description")#change to bigger text? 
    pub_hidden = models.BooleanField(default=False, help_text="A flag to determine whether this item should be hidden from the site", verbose_name="Publication Hidden")
    # Metadata
    class Meta:
        db_table = "publications"
        ordering = ['pub_name']
        verbose_name = "publications"
        verbose_name_plural = "publications"
    # Methods
    def __str__(self):
        return self.pub_name
    
# Content Item (the actual links)
class ContentItem(models.Model):
    # Fields
    item_id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this content item", verbose_name='Item Id')
    item_title = models.CharField(max_length=256,blank=False,null=False, help_text="The title of the content item i.e blog title", verbose_name="Item Title") 
    item_url = models.URLField(blank=False,null=False, help_text="URL of the content item i.e the url of the article", verbose_name="Item URL")
    item_datepublished = models.DateField(null=True, blank=True, help_text="The date the item was published at it's source, if possible to attain", verbose_name="Item Date Published")
    item_datecreated = models.DateTimeField(auto_now_add=True,null=True, blank=True, help_text="The date the item was created in the app, set to the time of creation", verbose_name= "Item Date Created")
    item_source = models.ForeignKey(Publications, on_delete=models.RESTRICT, null=False, help_text="The source of the item is the name of where it came from i.e SuperJump", verbose_name="Item Source")
    item_votecount = models.IntegerField(default=0,blank=False,help_text="Counts the items popularity", verbose_name="Item Vote Count")
    item_hidden = models.BooleanField(default=False, help_text="A flag to determine whether this item should be hidden from the site", verbose_name="Item Hidden")
    item_curated = models.BooleanField(default=False, help_text="A flag to determine whether this item should be elevated to the curated section", verbose_name="Item Curated")
    # Metadata
    class Meta:
        db_table = "content_item"
        indexes = []
        ordering = ['-item_datepublished']
        verbose_name = "Item"
        verbose_name_plural = "Items"
        constraints = [models.UniqueConstraint(fields=["item_url"], name='unique_url')]
    # Methods
    def __str__(self):
        return self.item_title
    
    def pub_guid(self):
        return Publications.objects.get(pub_id = self.item_source.pk).pub_id
    
# Content Votes
class Votes(models.Model):
    # Fields 
    vote_id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this vote", verbose_name="New Vote Id" )
    item_id = models.UUIDField(default=uuid.uuid4, help_text="ID of content item", verbose_name="Item ID")
    session_id = models.CharField(max_length=128,blank=False,null=False,help_text="Session ID of the person making the vote", verbose_name="Session ID")
    vote_date = models.DateField(default=timezone.now,help_text="Date vote occured",verbose_name="Date Voted")
    # Metadata
    class Meta:
        db_table = "votes"
        ordering = ['-vote_date']
        verbose_name = "Votes"
        verbose_name_plural = "Votes"
    # Methods
    def __str__(self):
        return str(self.vote_id)

# Publication Form (form for requests)
class PubRequest(models.Model):
    # Fields
    pubreq_id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this new source request", verbose_name="New Source Id" )
    pubreq_url = models.CharField(blank=False,max_length=2000,help_text="URL of the website top domain", verbose_name="Source URL")
    pubreq_feed = models.CharField(blank=False,max_length=2000,help_text="URL of the websites Feed, i.e RSS", verbose_name="Source Feed URL")
    pubreq_name = models.CharField(blank=False,max_length=256,help_text="Name of the person making contact", verbose_name="Contact Name")
    pubreq_email = models.EmailField(blank=False,help_text="The email of the person making contact", verbose_name="Email Address")
    pubreq_notes = models.TextField(blank=True,null=True,max_length=2000,help_text="Notes about the request", verbose_name="Additional Information")
    pubreq_complete = models.BooleanField(default=False, help_text="A flag to determine whether this request has been handled", verbose_name="Source Request Status")
    pubreq_date = models.DateField(default=timezone.now,help_text="Date request was submitted",verbose_name="Date Submitted")
    # Metadata
    class Meta:
        db_table = "publication_request"
        ordering = ['-pubreq_date']
        verbose_name = "Publication Request"
        verbose_name_plural = "Publication Requests"
    # Methods
    def __str__(self):
        return self.pubreq_name 

# Contact Form (form for comments)
class ContactRequest(models.Model):
    contact_id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this new contact request", verbose_name="Contact Id" )
    contact_name = models.CharField(blank=False,max_length=256,help_text="Name of the person making contact", verbose_name="Contact Name")
    contact_email = models.EmailField(blank=False,help_text="The email of the person making contact", verbose_name="Contact Email")
    contact_notes = models.TextField(blank=False,max_length=2000,help_text="Notes about the contact request", verbose_name="Additional Information")
    contact_complete = models.BooleanField(default=False, help_text="A flag to determine whether this request has been handled", verbose_name="Contact Request Status")
    contact_date = models.DateField(default=timezone.now,help_text="Date request was submitted",verbose_name="Date Submitted")
    # Metadata
    class Meta:
        db_table = "contact_request"
        ordering = ['-contact_date']
        verbose_name = "Contact Request"
        verbose_name_plural = "Contact Requests"
    # Methods
    def __str__(self):
        return self.contact_name 

contentfeed/templates/feed.html
{% extends "standard.html" %}
{% load mathfilters %}
{% block content %}
{% with p_multi=page_obj.number|add:"-1"%}
{% with p_change=plimit|mul:p_multi %}
    <!-- Editors Pick  -->
    <div class="container grid-lg p-relative p-0">
    <div id="ed-pick" class="card">
        <div class="card-header">
          <div class="card-title h1">Editors Pick</div>
        </div>
        <div class="card-body pt-2">
            {% for c in curated_items %}
            <div id="edlink" class="pb-2"><a href="{{c.item_url}}" onclick="upvote('{{c.item_id}}','{{session_id}}','{{ csrf_token }}')" class="vote-link" target="_blank">{{c.item_title}}</a></div>
            <div class="mb-2"><span id="edchip" class="chip bg-yellow"><a class="tdn" href="/publication/{{c.pub_guid}}">{{c.item_source}}</a></span></div>
            {% empty %}
            <p>No items to display</p>
            {% endfor %} 
        </div>
      </div>
    </div>
    <!-- Tabs  -->
    <div class="container grid-lg pt-2">
    <ul class="tab tab-block">
        <li class="tab-item">
          <a href="/" {% if t_view == 0 %} class="active" {% endif %}>Trending</a>
        </li>
        <li class="tab-item">
          <a href="new" {% if t_view == 1 %} class="active" {% endif %}>Newest</a>
        </li>
        <li class="tab-item">
          <a href="/old" {% if t_view == 3 %} class="active" {% endif %}>Oldest</a>
        </li>
        <li class="tab-item">
          <a href="/random" {% if t_view == 2 %} class="active" {% endif %}>Random</a>
        </li>
      </ul>
    </div>
    <!-- Content Feed -->
    <div class="container grid-lg">
    {% for i in content_items %}
        <div class="tile mt-2">
            {% if page_obj.number > 1 %}
            <div class="tile-icon">{{forloop.counter|add:p_change}}</div>
            {% else %}
                {% if forloop.counter < 10 %}
                <div class="tile-icon">0{{forloop.counter}}</div>
                {% else %}
                <div class="tile-icon">{{forloop.counter}}</div>
                {% endif %}
            {% endif %}
            <div class="tile-content">
                <div class="pb-1"><a href="{{i.item_url}}" onclick="upvote('{{i.item_id}}','{{session_id}}','{{ csrf_token }}')" target="_blank">{{i.item_title}}</a></div>
                <div>
                    <button id="id-{{i.item_id}}" class="btn chip bg-dark mr-2 text-primary fnt-semi" onclick="upvote('{{i.item_id}}','{{session_id}}','{{ csrf_token }}')">Vote</button>
                    <span class="chip"><a class="tdn" href="/publication/{{i.pub_guid}}">{{i.item_source}}</a></span>
                <!-- Admin only buttons -->
                {% if user.is_authenticated %}
                <span class="chip bg-orange"><a class="tdn" href="feature/{{i.item_id}}">Feature</a></span>
                <span class="chip bg-orange"><a class="tdn" href="hide/{{i.item_id}}">Hide</a></span>
                {% endif %}
                </div>
            </div>
        </div>
    <div class="divider"></div>
    {% empty %}
        <p>No Content to display</p>
    {% endfor %} 
    <div class="columns pagination">
        <div class="column col-6 step-links">
            {% if page_obj.has_previous %}
            <div id="header-medium">
                <span class="bg-yellow px-1r fnt-med hvr_out"><a class="tdn" href="?page={{ page_obj.previous_page_number }}">BACK</a></span>
              </div>
            {% endif %}
        </div>
        <div class="column col-6 step-links text-right">
            {% if page_obj.has_next %}
            <div id="header-medium">
                <span class="bg-yellow px-1r fnt-med hvr_out"><a class="tdn" href="?page={{ page_obj.next_page_number }}">NEXT</a></span>
              </div>
            {% endif %}
        </div>
    </div>
</div>
    {% endwith %}
    {% endwith %}
{% endblock %}

contentfeed/templates/publications.html
{% extends "base.html" %}
{% block content %}
<div id="normal" class="row">
    <h1>Publications</h1>
</div>
<div id="pubgrid" class="row">
    {% for p in publications %}
    <div id="pubcol" class="column column-50">
        <div id="pubitem" class="row">
            <div id="puptitle" class="column column-40">{{p.pub_name}}</div>
            <div id="pubdesc" class="column">{{p.pub_description}}</div>
        </div>
    </div>
    {% empty %}
    <p>No Publications to display, possible query error.</p>
    {% endfor %} 
</div>
<!-- Publication Request -->
<div id="normal" class="row">
    <h2>Request to add your publication</h2>
</div>
<div id="norm-grid" class="row">
    <div id="norm-point" class="column"><p>-</p></div>
    <div id="norm-item" class="column"><p>Your site needs to have an RSS feed, I'll be working on other methods of acquiring data in the future but at the moment its RSS only.</p></div>
</div>
<div id="norm-grid" class="row">
    <div id="norm-point" class="column"><p>-</p></div>
    <div id="norm-item" class="column"><p>Your site needs to be contain a decent amount of content about video games, game development, or the video game industry.</p></div>
</div>
<div id="norm-grid" class="row">
    <div id="norm-point" class="column"><p>-</p></div>
    <div id="norm-item" class="column"><p>While some paywalling is acceptable, i.e Substack, there also needs to be freely-available content.</p></div>
</div>
<div id="norm-grid" class="row">
    <div id="norm-point" class="column"><p>-</p></div>
    <div id="norm-item" class="column"><p>The clear majority of your content needs to be editorial, if every post is the 'latest' news or a wall of reviews, it's not the brand of content I'm looking to highlight.</p></div>
</div>
<div id="norm-grid" class="row">
    <div id="norm-point" class="column"><p>-</p></div>
    <div id="norm-item" class="column"><p>While we have no problem with your site having an infrequent posting schedule, in order to review your site we would like to see at least one to two articles posted in good faith in the past twelve months.</p></div>
</div>
<div id="norm-grid" class="row">
    <div id="norm-point" class="column"><p>-</p></div>
    <div id="norm-item" class="column"><p>The review of your site will not be undertaken in any set timeframe.</p></div>
</div>
<div id="norm-grid" class="row">
    <div id="norm-point" class="column"><p>-</p></div>
    <div id="norm-item" class="column"><p>We reserve the right to reject your site as a new source based on grounds not listed above, we'll be in contact with you about that process and explain our reasoning if I have concerns.</p></div>
</div>
<div id="formform" class="column">
    <form method="POST">
        {% csrf_token %}
        {{ NewSourceRequest }}
        <br>
        <input type="submit" value="Submit">
    </form>
</div>
{% endblock %}

contentfeed/templates/publist.html
{% extends "standard.html" %}
{% block content %}
<!-- Heading & Description -->
<div class="container grid-lg p-relative">
    {% for p in pub_detail %}
    <div id="header-big">
        <span class="bg-yellow fnt-extra px-1r">{{p.pub_name}}</span>
    </div>
    <span>
        {{p.pub_description}}
        Click <a href="{{p.pub_url}}">here</a> to go to the publications website.
    </span>
    {% empty %}
    {% endfor %}
<!-- Dropdown -->
<div id="pub-drop">
    <a href="#" onclick="showPublications()" class="btn bg-dark text-primary" tabindex="0">Change Publication</a>
</div>
<!-- Modal -->
<div class="modal" id="pub-modal">
    <a href="#close" class="modal-overlay" aria-label="Close"></a>
    <div class="modal-container">
            <div class="modal-header">
                <a href="#close" onclick="showPublications()" class="btn btn-clear float-right" aria-label="Close"></a>
                <div class="modal-title h2 mt-1r">Select a Publication</div>
            </div>
            <div class="modal-body">
                <ul>
                    {% for l in pub_list %}
                    <li><a href="/publication/{{l.pub_id}}">{{l.pub_name}}</a></li>
                    {% empty %}
                    {% endfor %}
                </ul>
            </div>
    </div>
</div>

</div>
<!-- Results -->
<div class="container grid-lg mb-1r">
<div id="header-medium">
    <span class="bg-yellow fnt-extra px-1r">Articles</span>
</div>
    <span>See all articles by this publication, ordered by their publication date in descending order. Older articles may not appear in this list.</span>
</div>
<div class="container grid-lg">
    {% for i in pub_items %}
    <div class="tile mt-2">
        <div class="tile-icon"><i class="icon icon-minus"></i></div>
        <div class="tile-content">
          <div class="pb-1">
            <a href="{{i.item_url}}" onclick="upvote('{{i.item_id}}','{{session_id}}','{{ csrf_token }}')" target="_blank">{{i.item_title}}</a>
          </div>
          <div><span class="chip">{{i.item_datepublished}}</span></div>
        </div>
      </div>
    {% empty %}
    <p>No Results</p>
    {% endfor %}
  </div>
{% endblock %}

contentfeed/templates/sites.html
{% extends "standard.html" %} {% block content %}
<div class="container grid-lg p-0">
  <!-- Page Title -- -- -- -- -- -- -- -- -- -- -- -- -- -- -->
  <div id="header-big">
    <span class="bg-yellow fnt-extra px-1r">Sites</span>
  </div>
  <!-- Blurb Text -- -- -- -- -- -- -- -- -- -- -- -- -- -- -->
  <div class="px-1r">
    <span>
      Read more about the amazing publications featured here on Reconnect. If
      you wish to submit your site for Reconnect, read the rules and fill out
      the form at the bottom.
    </span>
  </div>
  <!-- Site List -- -- -- -- -- -- -- -- -- -- -- -- -- -- -->
  <div class="accordion pt-1r">
    <input type="checkbox" id="accordion-1" name="accordion-checkbox" hidden>
    <label class="accordion-header px-1r" for="accordion-1">
      <i class="icon icon-arrow-right mr-1"></i>
      Click here to expand the list of sites.
    </label>
    <div class="accordion-body">
  <!--  Site List-->
  <div class="columns mt-2r">
    {% for p in publications %}
    <div class="column col-md-auto col-6 p-0">
      <div class="columns m-2 bt-2">
        <div class="column col-6 p-0">
          <h3><a href="/publication/{{p.pub_id}}" target="_blank">{{p.pub_name}}</a></h3>
        </div>
        <div class="column col-6"><p>{{p.pub_description}}</p></div>
      </div>
    </div>
    {% empty %}
    <div class="columns">
      <div class="column col-6"><h4>Error</h4></div>
      <div class="column col-6">
        <p>Query has not returned any publication</p>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
</div>
  <!-- Rules -- -- -- -- -- -- -- -- -- -- -- -- -- -- -->
  <div id="header-medium" class="mb-2r">
    <span class="bg-yellow fnt-extra p-2">Site Request Rules</span>
  </div>
  <!-- Rule Point -->
  <div class="columns mt-1r">
    <!-- Left Col -->
    <div class="column pl-1r w60 col-auto mr-1r">
      <div id="small-box" class="bg-dark text-center">
        <i class="icon icon-arrow-right text-primary"></i>
      </div>
    </div>
    <!-- Right Col -->
    <div class="column col-9">
      <span>
        Your site needs to have an RSS feed. 
      </span>
    </div>
  </div>

  <!-- Rule Point -->
  <div class="columns mt-1r">
    <!-- Left Col -->
    <div class="column pl-1r w60 col-auto mr-1r">
      <div id="small-box" class="bg-dark text-center">
        <i class="icon icon-arrow-right text-primary"></i>
      </div>
    </div>
    <!-- Right Col -->
    <div class="column col-9">
      <span>
        While some pay-walling is acceptable, i.e Substack, there also needs to
        be freely-available content.
      </span>
    </div>
  </div>
  <!-- Rule Point -->
  <div class="columns mt-1r">
    <!-- Left Col -->
    <div class="column pl-1r w60 col-auto mr-1r">
      <div id="small-box" class="bg-dark text-center">
        <i class="icon icon-arrow-right text-primary"></i>
      </div>
    </div>
    <!-- Right Col -->
    <div class="column col-9">
      <span>
        The clear majority of your content needs to be editorial, if every post
        is the 'latest' news or a wall of reviews, it's not the brand of content
        I'm looking to highlight.
      </span>
    </div>
  </div>
  <div id="header-medium" class="mt-2r">
    <span class="bg-yellow fnt-extra p-2">Request Form</span>
  </div>
  <div class="container clearfix d-block">
    <div class="container grid-xs float-left p-0">
      <!-- Form submission Toast -->
      {% if fvalid == 1 %}
      <div class="toast toast-success">
        <button class="btn btn-clear float-right"></button>
        Form Submitted Successfully
      </div>
      {% elif fvalid == 2 %}
      <div class="toast toast-error">
        <button class="btn btn-clear float-right"></button>
        Form not submitted, review your entry and try again.
      </div>
      {% endif %}
      <!-- Form -->
      <form method="POST">
        {% csrf_token %} {{ cform.non_field_errors }}
        <div class="form-group">
          {{ cform.subject.errors }}
          <label class="form-label" for="id_pubreq_name">Your Name</label>
          <input
            class="form-input"
            type="text"
            name="pubreq_name"
            maxlength="200"
            id="id_pubreq_name"
          />
          <label class="form-label label-sm"
            >How do you want me to address you?.</label
          >
        </div>
        <div class="form-group">
          {{ cform.subject.errors }}
          <label class="form-label" for="id_pubreq_email">Your Email</label>
          <input
            class="form-input"
            type="text"
            name="pubreq_email"
            maxlength="200"
            id="id_pubreq_email"
          />
          <label class="form-label label-sm"
            >I'll contact you at this address.</label
          >
        </div>
        <div class="form-group">
          {{ cform.subject.errors }}
          <label class="form-label" for="id_pubreq_url">Website URL</label>
          <input
            class="form-input"
            type="url"
            name="pubreq_url"
            maxlength="2000"
            id="id_pubreq_url"
          />
          <label class="form-label label-sm"
            >The address of your website.</label
          >
        </div>
        <div class="form-group">
          {{ cform.subject.errors }}
          <label class="form-label" for="id_pubreq_feed">Feed URL</label>
          <input
            class="form-input"
            type="url"
            name="pubreq_feed"
            maxlength="2000"
            id="id_pubreq_feed"
          />
          <label class="form-label label-sm"
            >The address of your feed i.e yoursite.com/rss.</label
          >
        </div>
        <div class="form-group">
          {{ cform.subject.errors }}
          <label class="form-label" for="id_pubreq_notes">Notes</label>
          <textarea
            class="form-input"
            name="pubreq_notes"
            rows="5"
            maxlength="2000"
            id="id_pubreq_notes"
          ></textarea>
          <label class="form-label label-sm"
            >Please include any additional information about your
            request.</label
          >
        </div>
        <input class="btn btn-primary mb-2r" type="submit" value="Submit" />
      </form>
    </div>
  </div>
</div>
{% endblock %}

contentfeed/templates/sources.html
{% extends "standard.html" %} {% block content %}
<div class="divider"></div>
<div class="container grid-lg">
  <!--  Site List-->
  <h2>Sources</h2>
  <div class="columns">
    {% for p in publications %}
    <div class="column col-md-auto col-4 p-0">
      <div class="columns m-2" id="sitegrid">
        <div class="column col-6 p-0"><h4><a href="{{p.pub_url}}" target="_blank">{{p.pub_name}}</a></h4></div>
        <div class="column col-6"><p>{{p.pub_description}}</p></div>
      </div>
    </div>
    {% empty %}
    <div class="columns">
      <div class="column col-6"><h4>Error</h4></div>
      <div class="column col-6">
        <p>Query has not returned any publication</p>
      </div>
    </div>
    {% endfor %}
  </div>

  <!-- Rules -->
  <div class="pt-2"><h3>Request to add your Site</h3></div>
  <div class="tile">
    <div class="tile-icon">
      <div class="tile-icon"><i class="icon icon-minus"></i></div>
    </div>
    <div class="tile-content">
      <p>
        Your site needs to have an RSS feed, I'll be working on other methods of
        acquiring data in the future but at the moment its RSS only.
      </p>
    </div>
  </div>
  <div class="tile">
    <div class="tile-icon">
      <div class="tile-icon"><i class="icon icon-minus"></i></div>
    </div>
    <div class="tile-content">
      <p>
        Your site needs to be contain a decent amount of content about video
        games, game development, or the video game industry.
      </p>
    </div>
  </div>
  <div class="tile">
    <div class="tile-icon">
      <div class="tile-icon"><i class="icon icon-minus"></i></div>
    </div>
    <div class="tile-content">
      <p>
        While some pay-walling is acceptable, i.e Substack, there also needs to
        be freely-available content.
      </p>
    </div>
  </div>
  <div class="tile">
    <div class="tile-icon">
      <div class="tile-icon"><i class="icon icon-minus"></i></div>
    </div>
    <div class="tile-content">
      <p>
        The clear majority of your content needs to be editorial, if every post
        is the 'latest' news or a wall of reviews, it's not the brand of content
        I'm looking to highlight.
      </p>
    </div>
  </div>
  <div class="tile">
    <div class="tile-icon">
      <div class="tile-icon"><i class="icon icon-minus"></i></div>
    </div>
    <div class="tile-content">
      <p>
        While we have no problem with your site having an infrequent posting
        schedule, in order to review your site we would like to see at least one
        to two articles posted in good faith in the past twelve months.
      </p>
    </div>
  </div>
  <div class="tile">
    <div class="tile-icon">
      <div class="tile-icon"><i class="icon icon-minus"></i></div>
    </div>
    <div class="tile-content">
      <p>
        The review of your site will not be undertaken in any set time frame..
      </p>
    </div>
  </div>
  <div class="tile">
    <div class="tile-icon">
      <div class="tile-icon"><i class="icon icon-minus"></i></div>
    </div>
    <div class="tile-content">
      <p>
        I reserve the right to reject your site as a new source based on grounds
        not listed above, we'll be in contact with you about that process and
        explain our reasoning if I have concerns.
      </p>
    </div>
  </div>
  <div class="container grid-xs float-left p-0">
    <!-- Form submission Toast -->
    {% if fvalid == 1 %}
    <div class="toast toast-success">
      <button class="btn btn-clear float-right"></button>
      Form Submitted Successfully
    </div>
    {% elif fvalid == 2 %}
    <div class="toast toast-error">
      <button class="btn btn-clear float-right"></button>
      Form not submitted, review your entry and try again.
    </div>
    {% endif %}
    <!-- Form -->
    <form method="POST">
      {% csrf_token %} {{ cform.non_field_errors }}
      <div class="form-group">
        {{ cform.subject.errors }}
        <label class="form-label" for="id_pubreq_name">Your Name</label>
        <input
          class="form-input"
          type="text"
          name="pubreq_name"
          maxlength="200"
          id="id_pubreq_name"
        />
        <label class="form-label label-sm"
          >How do you want me to address you?.</label
        >
      </div>
      <div class="form-group">
        {{ cform.subject.errors }}
        <label class="form-label" for="id_pubreq_email">Your Email</label>
        <input
          class="form-input"
          type="text"
          name="pubreq_email"
          maxlength="200"
          id="id_pubreq_email"
        />
        <label class="form-label label-sm"
          >I'll contact you at this address.</label
        >
      </div>
      <div class="form-group">
        {{ cform.subject.errors }}
        <label class="form-label" for="id_pubreq_url">Website URL</label>
        <input
          class="form-input"
          type="url"
          name="pubreq_url"
          maxlength="2000"
          id="id_pubreq_url"
        />
        <label class="form-label label-sm">The address of your website.</label>
      </div>
      <div class="form-group">
        {{ cform.subject.errors }}
        <label class="form-label" for="id_pubreq_feed">Feed URL</label>
        <input
          class="form-input"
          type="url"
          name="pubreq_feed"
          maxlength="2000"
          id="id_pubreq_feed"
        />
        <label class="form-label label-sm"
          >The address of your feed i.e yoursite.com/rss.</label
        >
      </div>
      <div class="form-group">
        {{ cform.subject.errors }}
        <label class="form-label" for="id_pubreq_notes">Notes</label>
        <textarea
          class="form-input"
          name="pubreq_notes"
          rows="5"
          maxlength="2000"
          id="id_pubreq_notes"
        ></textarea>
        <label class="form-label label-sm"
          >Please include any additional information about your request.</label
        >
      </div>
      <input class="btn btn-col1" type="submit" value="Submit" />
    </form>
  </div>
</div>
{% endblock %}